---
- name: Redbox Inventory Sync
  hosts: localhost

  tasks:
  - name: trigger inventory sync
    uri:
      # url:  https://localhost/api/v1/projects/7/update/
      url: https://172.24.4.16/api/v2/inventories/2/update_inventory_sources/
      method: POST
      user: admin
      password: "This4now!"
      validate_certs: False
      force_basic_auth: yes
      status_code:
        - 200
        - 201
        - 202
    register: response
    changed_when: response.status == 201